name: Deploy to AWS EC2 UTS-Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to ECS
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.169.84.29 << 'EOF'
          cd /var/www/uts-backend
          sudo git pull origin main
          node app.js
        EOF
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}